"""initial schema

Revision ID: 2baf545b9e3e
Revises: 
Create Date: 2026-07-14 14:19:10.393359
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2baf545b9e3e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('platform', sa.Enum('MEET', 'ZOOM', 'TEAMS', 'OTHER', name='platform', native_enum=False), nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_language', sa.String(length=8), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('NORMALIZE', 'TRANSCRIBE', 'DIARIZE', 'ALIGN', 'TRANSLATE', 'MINUTES', 'GROUND', 'INDEX', name='jobtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_meeting_id'), 'jobs', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('minutes',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minutes_meeting_id'), 'minutes', ['meeting_id'], unique=False)
    op.create_table('recordings',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('track', sa.Enum('MIC', 'TAB', 'MIXED', name='track', native_enum=False), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('normalized_path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_meeting_id'), 'recordings', ['meeting_id'], unique=False)
    op.create_table('speakers',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('source', sa.Enum('LOCAL_TRACK', 'DOM', 'DIARIZATION', 'MANUAL', 'UNKNOWN', name='speakersource', native_enum=False), nullable=False),
    sa.Column('external_ref', sa.String(length=256), nullable=True),
    sa.Column('is_local_user', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_meeting_id'), 'speakers', ['meeting_id'], unique=False)
    op.create_table('minutes_items',
    sa.Column('minutes_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DECISION', 'ACTION_ITEM', 'OPEN_QUESTION', 'RISK', 'TOPIC', name='minutesitemtype', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('owner_speaker_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('segment_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('is_grounded', sa.Boolean(), nullable=True),
    sa.Column('grounding_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['minutes_id'], ['minutes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minutes_items_minutes_id'), 'minutes_items', ['minutes_id'], unique=False)
    op.create_table('segments',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('speaker_source', sa.Enum('LOCAL_TRACK', 'DOM', 'DIARIZATION', 'MANUAL', 'UNKNOWN', name='speakersource', native_enum=False), nullable=False),
    sa.Column('avg_logprob', sa.Float(), nullable=True),
    sa.Column('no_speech_prob', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_meeting_id'), 'segments', ['meeting_id'], unique=False)
    op.create_index('ix_segments_meeting_start', 'segments', ['meeting_id', 'start_ms'], unique=False)
    op.create_index(op.f('ix_segments_recording_id'), 'segments', ['recording_id'], unique=False)
    op.create_table('speaker_events',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('LOCAL_TRACK', 'DOM', 'DIARIZATION', 'MANUAL', 'UNKNOWN', name='speakersource', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_events_meeting_id'), 'speaker_events', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_speaker_events_speaker_id'), 'speaker_events', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_speaker_events_start_ms'), 'speaker_events', ['start_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_events_start_ms'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_speaker_id'), table_name='speaker_events')
    op.drop_index(op.f('ix_speaker_events_meeting_id'), table_name='speaker_events')
    op.drop_table('speaker_events')
    op.drop_index(op.f('ix_segments_recording_id'), table_name='segments')
    op.drop_index('ix_segments_meeting_start', table_name='segments')
    op.drop_index(op.f('ix_segments_meeting_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_minutes_items_minutes_id'), table_name='minutes_items')
    op.drop_table('minutes_items')
    op.drop_index(op.f('ix_speakers_meeting_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_recordings_meeting_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_minutes_meeting_id'), table_name='minutes')
    op.drop_table('minutes')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_meeting_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('meetings')
    # ### end Alembic commands ###
